### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#1]
tiny: EEPROM - OK
esp: DNS сервер - OK
tiny: CRC
esp: DHCP запоминать ip, если в следующий раз ip не подойдет, включить DHCP и получить новый
esp: 2й wi-fi - ждем реализации от WifiManager
сервер: БД - скоро
сервер: визуализация - не нужно

Hardware:
конденсатор 10мкФ по питанию от вибрации батареек. - пока не надо
питание: включать ESP-01. экономия ~10мкА 
UPD: ESP-01s почти ничего не потребляет.

tiny: заменить на  PIC16(L)F1454/5/9 или STM8L или TI430. 

Функции:
esp: OTA update https://www.bakke.online/index.php/2017/06/02/self-updating-ota-firmware-for-esp8266/#more-328
esp: добавить настройки кол-во литров/импульс, начальные показания, хвс/гвс - OK
esp: NTP сервер https://github.com/arduino-libraries/NTPClient/blob/master/examples/Basic/Basic.ino  - можно через Blynk. Не нужно, т.к. будет сайт.
esp: передача сетевых настроек на сервер - не нужно

Доп. функционал:
esp: добавить датчик температуры. следить за горячей/хол водой..
tiny: точные показания по времени
tiny: датчик протечек - некуда

**Comment by dontsovcmc** [comment]
Attiny хорошо бы заменить на современные аналоги: PIC16(L)F1454/5/9

**Comment by dontsovcmc** [comment]
- питания через EN
- срезы только при изменении. отправка по заполнению буфера. или раз в N дней.

**Comment by dontsovcmc** [comment]
Реализация без сервера:

1. добавить параметры в Web интерфейс счетчика
2. при просыпании, узнавать текущее время от NTP сервера. И при необходимости слать сообщение с текущими показаниями:
https://github.com/arduino-libraries/NTPClient/blob/master/examples/Basic/Basic.ino

**Comment by dontsovcmc** [comment]
1. добавить диод на reset
2. запустить общий код в Atmel Studio
3. проверить регистр MCUSR при включении. Там инфа о перезагрузке.
4. сделать EEPROM
6. Проверить резистор на EN
5. отладить в Atmel Studio

**Comment by dontsovcmc** [comment]
byte ResetSrc = MCUSR; // save reset source
  MCUSR = 0x00; //cleared for next reset detection
  if (ResetSrc & _BV(PORF)) Serial.println("PORF");
  if (ResetSrc & _BV(EXTRF)) Serial.println("EXTRF");
  if (ResetSrc & _BV(BORF)) Serial.println("BORF");
  if (ResetSrc & _BV(WDRF)) Serial.println("WDRF");

**Comment by dontsovcmc** [comment]
1. кнопка на SDA - GND.
2. переписать код
3.

**Comment by dontsovcmc** [comment]
1. потребление 2мА при включении?!
2. DNS сервер

может все таки можно без сервера?

**Comment by dontsovcmc** [comment]
У библиотеки Blynk есть возможность синхронизации времени.
1. добавить параметр: день рассылки
Если день рассылки не пустой:
    Если месяц отправки не равен текущему
         Отослать

https://github.com/blynkkk/blynk-library/blob/master/examples/Widgets/RTC/RTC.ino

**Comment by dontsovcmc** [comment]
Согласно [обзору STM8](https://www.terraelectronica.ru/news/5482) нам подходит этот: [STM8L051F3](https://docs-europe.electrocomponents.com/webdocs/1285/0900766b8128502b.pdf) на 20 пин. Можно взять и на 8 пин, но лучше больше, чтобы подключить датчик протечки и дополнительные входы.
PlatformioIO еще не поддерживает STM8L =(

**Comment by dontsovcmc** [comment]
ESP32:
https://habr.com/post/418573/#comment_18937991
ULP Pulse Counting Example
examples/system/ulp/ вот что пишут:
With the default configuration (20ms ULP wakeup period), average current consumption in deep sleep mode is 16uA.

**Comment by dontsovcmc** [comment]
Вот пример использования Радиомодуля с Attiny85. Т.к. мы автономны, нам нужно подавать на него питание. Это можно сделать, как отдельным стабилизатором, так и транзистором.

https://www.instructables.com/id/Mini-weather-station-with-Attiny85/

Проект с подключением LCD экрана тоже там.

**Comment by dontsovcmc** [comment]
![6cd91000-8681-11eb-8bc4-93dc637954d3](https://user-images.githubusercontent.com/6192152/149360414-92541db0-0a21-4915-8b61-e894fbfbe2aa.jpeg)

**Comment by heX16** [comment]
![waterius](https://user-images.githubusercontent.com/3930496/149906477-6aa47cdd-f714-4546-85ff-5541c60260a2.jpeg)


"крутилки" которые с право внизу изменил - уменьшил у них "saturation", иначе они сильно бросаются в глаза и ухудшают восприятие картинки.

**Comment by dontsovcmc** [comment]
> ![waterius](https://user-images.githubusercontent.com/3930496/149906477-6aa47cdd-f714-4546-85ff-5541c60260a2.jpeg)
> 
> @dontsovcmc, вот так мне кажется лучше выглядит? - "крутилки" которые с право внизу изменил, уменьшил у них "saturation", иначе они сильно бросаются в глаза и ухудшают восприятие картинки.

Секс! Гордость за комьюнити! Спасибо! Хотите пул реквест на титул сделайте?)) будете в разработчиках ааха
