### ISSUE TITLE
Заменить разъемы на Wago 235

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#107]
"хватит издеваться над пользователями", говорит мой дизайнер =)

Эти разъемы гораздо понятнее людям. И дырка под провод больше:
![pctdetail 820-283 1](https://user-images.githubusercontent.com/6192152/69563637-894fc580-0fc2-11ea-868c-bf5712524ea0.jpg)

wago 235-770 (красные)
wago 235-774 (синии)
wago 235-400 (синий терминатор)
wago 235-800 (красный терминатор)

**Comment by OloloevReal** [comment]
Эх, клемники жир блеск красота, но где их взять в шаговой доступности. В широко известном магазине который упаковывает детальки в прозрачные пакетики их нет

**Comment by dontsovcmc** [comment]
> Эх, клемники жир блеск красота, но где их взять в шаговой доступности. В широко известном магазине который упаковывает детальки в прозрачные пакетики их нет

Это да, может ИП как-то мне поможет.

**Comment by dontsovcmc** [comment]
Заказал фантастически красивые разъёмчики - красненькие и синенькие! Обещают 50-90 дней доставки... ппц. Быстрее друзей попрошу привезти из Европы.
Придется поднимать цену за пафос и удобство втыкания проводов =)

**Comment by dontsovcmc** [comment]
Эти разъемы лучше, чем текущие, но тоже не панацея. Пока закрою задачу до лучших времен.
