### ISSUE TITLE
Индикация низкого заряда

### ISSUE THREAD

**Issue by OloloevReal** [dontsovcmc/waterius#109]
В копилку идей - в режиме TRANSMIT_MODE (по таймеру или при нажатии кнопки) если напряжение питания ниже определенного значения (какого?) не включать WiFi, а сигнализировать о недостаточном питании, например, пятью короткими вспышками LED1

Это позволит продолжить собирать данные со счетчиков еще очень продолжительное время, но не передавать их. А при попытки ручной передачи сразу станет понятно в чем дело.

Т.к. индикатор LED1 подключен к ESP поморгать индикатором можно будет только разбудив ее.

**Comment by dontsovcmc** [comment]
О! Вот зачем моргать надо, когда плохо! А я никак не мог понять, зачем гирлянды вешают на устройства. 
Есть нюанс: просадка идет во время DHCP т.е. за 0.1 секунду с включения не понять, что с питанием плохо =(. 

Я вставил в Ватериус батарейки ИКЕА, которым 5 лет, и включил отправку раз в 30 минут:
Графики "усредненные":
![photo_2019-12-04_00-06-43](https://user-images.githubusercontent.com/6192152/70089836-0960d580-162a-11ea-8a8b-a5d1d5e5ed98.jpg)

![photo_2019-12-04_00-06-47](https://user-images.githubusercontent.com/6192152/70089865-1382d400-162a-11ea-913f-0dd62f9a03fa.jpg)

Вот 2 точки включения
![photo_2019-12-04_00-06-38](https://user-images.githubusercontent.com/6192152/70089880-1b427880-162a-11ea-9024-0811248b031c.jpg)

Это график падения напряжения за время подключения к роутеру ~5сек

**Comment by dontsovcmc** [comment]
У ESP нет аналогового входа =(. Вариант с ключом на транзисторе и читать свободный пин RX только.
