### ISSUE TITLE
Не подключается к цифровому паролю 16 символов

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#114]
У 1го клиента, роутер ASUS не подключился. У меня работает.
Я знаю бывают проблемы с паролем 12345678. 
Возможно стоит erase_flash перед прошивкой сделать.
У вас есть опыт цифровых паролей? Работает?

**Comment by s1mb1o** [comment]
Попробуйте вместо 12345678 (ASCII) написания использовать HEX-запись  3132333435363738
