### ISSUE TITLE
Версия в герметичном боксе и с поддержкой датчиков протечки

### ISSUE THREAD

**Issue by badenbaden** [dontsovcmc/waterius#128]
Добрый день!

Евгений! Повторил Ваше устройство, спасибо, что делитесь!))
Хочется иметь возможность подключить большее количество счетчиков (например у меня есть 2 стояка и проложен провод между ними) для использования 1 устройства для всех стояков.
Также хочется иметь датчики протечки по нескольким зонам.
Герметичный корпус тоже очень неплохо было бы иметь.

Вот мои мысли:
Т.к. attiny85 не имеет столько ног, то взять предлагаю attiny84 (тем более, что доработка кода там минимальна). Стоимости этих микросхем почти сопоставимы, разница в размерах не критична.
Герметичный корпус на базе распределительной коробки с задатками герметичности.
Обработка датчика протечки по 2 зонам.

Возможные проблемы:
Увеличение количества сохраняемых показаний счетчиков (если их будет больше 2х) повлечет за собой меньший ресурс eeprom.
Как поведет себя attiny при подключении счетчика длинным кабелем.
Возможно увеличится энергопотребление.

Изыскания:
В строительном магазине нашел очень красивую распределительную коробку от ABB. Класс защиты IP65 (т.е. полная защита от пыли и защита от водяных струй), думаю больше и не нужно, защита от морских волн и погружения на 1 метр в квартире рассматривать не стоит.
Кабельные вводы встроены в коробку методом двойной экструзии. Просто прокалываешь шилом или отверткой отверстие и вставляешь кабели. Ввод работает как сальник. Стоимость коробки - 88 рублей. Внутри есть возможность установить и закрепить плату. Вот ее фотки.

![photo_2020-03-25_13-18-42](https://user-images.githubusercontent.com/16225816/77526290-657e8c80-6e9b-11ea-83b8-3d9d1e2e70c2.jpg)
![photo_2020-03-25_13-18-47](https://user-images.githubusercontent.com/16225816/77526371-7deea700-6e9b-11ea-9f55-452be063105d.jpg)
![photo_2020-03-25_13-18-50](https://user-images.githubusercontent.com/16225816/77526385-83e48800-6e9b-11ea-94e4-00b10f017cb5.jpg)

Вот мои наброски этой конструкцией в 3d.

![abb-ap9-2](https://user-images.githubusercontent.com/16225816/77526818-3b799a00-6e9c-11ea-95e0-8ecd36c6a5f9.jpg)
![abb-ap9-3](https://user-images.githubusercontent.com/16225816/77526829-3f0d2100-6e9c-11ea-9419-ad5361870cab.jpg)
![abb-ap9](https://user-images.githubusercontent.com/16225816/77526842-43393e80-6e9c-11ea-9f8e-ceedd29df9a0.jpg)

Кнопку можно нажимать через подвижный ввод. Светодиод фиксируется в соседнем вводе. ESP между ними (не нарисовал на эскизе).

Собственно для чего я это написал. Заменить на тини84 я могу, плату развести тоже могу, а вот программер из меня хреновый)). Евгений, если есть желание помочь с адаптацией прошивки под тини84 с заявленными плюшками, буду очень рад. В свою очередь предоставлю отчет о проделанной работе, выложу фото получившегося.

**Comment by dontsovcmc** [comment]
Добрый день! Да, вы все правильно пишите!
Хочется СТМ32 конечно, но пока желающих нет на него переписать прошивку :(.

Смотрите, я могу помочь с прошивкой, но мне сильно быстрее будет это делать имея плату на руках. Сможете тогда прислать плату обычным письмом и тиньку84? Я оплату скину.

По энергопотреблению: надо МОСФЕТом отключать ЕСП полностью - вот где главная проблема. Она только по даташитам ничего не потребляет, а на деле в зависимости от партии от 2 до 30мкА во сне. Там еще SDRAM же. Если сможете с этим помочь, будет замечательно.
А увеличение входов не сильно повлияет на него.
Можно сразу ЕСП12 поставить, кстати. Чтобы потом ОТА сделать.

**Comment by badenbaden** [comment]
Конечно смогу прислать. Займусь на днях платкой. ЕСП12 только из-за 4 мб памяти?

**Comment by dontsovcmc** [comment]
> Конечно смогу прислать. Займусь на днях платкой. ЕСП12 только из-за 4 мб памяти?

Плюсы ЕСП в 4мб памяти, потом кстати можно попробовать сделать обновление прошивки attiny84. Но думаю, лучше на СТМ32 перейти все таки.

**Comment by badenbaden** [comment]
Набросал схему. Хотелось бы комментариев - вдруг что не так. 
У контроллера есть 1 свободная нога, может кнопку перенести на свободный пин?
Ну и схему первичной прошивки тини и есп надо проверить.

![Schematic_Water count_attiny861_20200326222117](https://user-images.githubusercontent.com/16225816/77688426-1e82bb00-6fb1-11ea-9134-c81cec0bf1f3.png)

В протеусе накидал симуляцию ключа для включения есп. Полно дешевых подходящих транзисторов, но собственный ток утечки около 3 мкА. Это конечно меньше 30, но больше 2х. 
А вот с NVTR4503NT1G или NVTR4501NT1G, опять же по данным протеуса, утекает от 0 до 0,01 мкА!!! Надо протестить такой вариант в реальной схеме. 

Не включено:
![img-2020-03-26-22-34-48](https://user-images.githubusercontent.com/16225816/77689163-458dbc80-6fb2-11ea-8893-0c6684667651.png)

Включено:
![img-2020-03-26-22-35-46](https://user-images.githubusercontent.com/16225816/77689187-4fafbb00-6fb2-11ea-82b3-b2a01fde393c.png)

**Comment by dontsovcmc** [comment]
1. ESP точно надо через полевик выключать. Там только через светодиод (ногу TX) утекает 3мкА =(.
вот тут я еще силовые ключи выписал: https://github.com/dontsovcmc/waterius/issues/3#issuecomment-380848998
по транзисторам помочь не могу - нужен электронщик. может что на форумах пишут? должны же быть энергоэффективные схемы с отключением ЕСП.
 
2. Alarm и wakeleak по своей сути одинаковые входы - везде надо будет будить устройство и передавать состояние входов.
R17 убрать, а контакты 2-4-6 замкнуть. R16 - сделать 300ом.  Возможно вместо него следует дроссель поставить - для длинных проводов наводки убирать.
В целом защита от перезагрузки есть в прошивке.

3. R19, R18 тоже убираются. Для протечки не нужно дополнительных. Достаточно Аналогового входа. Внутри Тиньки есть 20к подтягивающие резисторы. Мы их включаем и сравниваем уровень с покоем. 

4. Вообще говоря, возможно нельзя ESP включать так, как вы предлагаете, лишая GND. Надо со спецами говорить. МК может быть плохо, от того, что питание подано, а земли нет.

5. MCP1700T-3002. На 3В.

**Comment by badenbaden** [comment]
6. Значит с кнопкой решили. Ставлю на свободный пин.
5. Точно! Чего же мне взбрело 3.3 поставить. И в действующую плату я на 3.3 поставил))).
4. Можно коммутировать Р-канальным + питания. Но я особой разницы не вижу в данном случае. Как МК может поплохеть, если + заведен на все пины, земли (-) нет, значит и цепи нет. Она только через SDA\SCL соединена с тинькой, да и те подтянуты к питанию. Когда вставляем батарейки, мы же не думаем - как вставить, сначала плюсовую или минусовую клемму. 
2 и 3. Waterleak1 и Waterleak2 это 2 разных входа датчиков протечки, чтобы по зонам определять место самой протечки (на клемме не изменил название, там оба Waterleak1). ALARM - это выход, для информирования или запуска сценариев на внешних устройствах. Также к этому выходу бы прикрутить пищалку или светодиод. R17 думаю нужно оставить, чтобы они не влияли друг на друга. R18, R19 подтягивают входы к питанию, без них что будет на входе с проводом 2-3 метра? И при протечке должно меняться сопротивление между контактами, а если нет подтяжки (в нашем случае это ведь резисторный делитель), то контроллер не поймет разницу между сопротивлением датчика 1 килоом и 1мегаомом - все будет казаться землей.

**Comment by badenbaden** [comment]
"Причесал" схему.  Добавил порты для прошивки. Резисторы R18 R19 пока оставил, в крайнем случае их номинал меняется на раз-два, либо ставится перемычка.


![Schematic_Water count_attiny861_20200327110231](https://user-images.githubusercontent.com/16225816/77734842-7dc8e580-701a-11ea-8298-a32562777bd8.png)

**Comment by dontsovcmc** [comment]
Я думаю стоит ставить резистор прям в датчик протечки. Тогда можно будет обрыв линии детектировать, что важно.
Да, R18,19 не мешают. В идеале там пусто будет.
А R30 зачем?

**Comment by dontsovcmc** [comment]
Вспомнил еще один плюс от такого Ватериуса: возможность прикрепить внешнюю антенну. Правда это все колхозить только... https://www.youtube.com/watch?v=fQIwG2ooE9k (

**Comment by OloloevReal** [comment]
Добрый день! Это не здоровый способ питания esp, может быть утечка в таком случае.
Ставьте отдельный регулятор с EN входом, либо ESP как нагрузку ставьте в коллектор транзиторного ключа.
Как-то так:
![post-127757-0-89281500-1357902137](https://user-images.githubusercontent.com/38255298/77786346-b5617d00-706e-11ea-9d3b-6fcf335fd8be.jpg)

Или на полевых, разницы нет.

**Comment by dontsovcmc** [comment]
@OloloevReal Да, я склоняюсь к вашему мнению. 
О, вот есть пример, когда по кнопке подается питание и сохраняется до отключения:  https://www.makermoekoe.net/post/a-dashbutton-like-thing-called-octoclick

В плате Adafruit используется DMG3415 .. Вот бы европейский аналог найти. Мне кажется это то, что нужно.
![adafruit_products_schem](https://user-images.githubusercontent.com/6192152/77789446-12136680-7074-11ea-976c-7bce2983cd7f.png)

**Comment by badenbaden** [comment]
> А R30 зачем?
Защита от выгорания порта при коротком замыкании.

**Comment by dontsovcmc** [comment]
@badenbaden КЗ на землю не страшно. Посмотрите, здесь про устройство портов: http://easyelectronics.ru/avr-uchebnyj-kurs-ustrojstvo-i-rabota-portov-vvoda-vyvoda.html
Для проверки входа мы:
1. включаем подтягивающий резистор
2. проверяем уровень компаратором
3. выключаем подтягивающий резистор

**Comment by badenbaden** [comment]
> Вспомнил еще один плюс от такого Ватериуса: возможность прикрепить внешнюю антенну. Правда это все колхозить только... https://www.youtube.com/watch?v=fQIwG2ooE9k (

> 
Зачем колхозить, когда есть вот такой модуль - ESP07

![104](https://user-images.githubusercontent.com/16225816/77792056-bf887900-7078-11ea-88af-cb6922db1bc5.jpg)

![E103-W01-IPX-Wifi-2-4-GHz-100mW-ESP8266EX-100m-IPX](https://user-images.githubusercontent.com/16225816/77792331-4178a200-7079-11ea-8e89-2743ff5611b6.jpg)

Выводы полностью совместимы.

**Comment by badenbaden** [comment]
> @badenbaden КЗ на землю не страшно. Посмотрите, здесь про устройство портов: http://easyelectronics.ru/avr-uchebnyj-kurs-ustrojstvo-i-rabota-portov-vvoda-vyvoda.html
Для проверки входа мы:

включаем подтягивающий резистор
проверяем уровень компаратором
выключаем подтягивающий резистор

> 
Я не догоняю. Как подтягивающий резистор защитит от КЗ? ALARM это выход. Если порт выключен, то все хорошо. А если я перепутал и замкнул землю и ALARM. При возникновении тревоги контроллер подаст на этот выход питание. Порт максимум можно нагрузить на 40 мА (по крайней мере в атмега328 так). При КЗ порт выгорит моментально. А если стоит резистор, то КЗ нет и при данном номинале нет и превышения по току. 
Есть такой популярный контроллер МегаД, так там каждый порт так защищен.

**Comment by dontsovcmc** [comment]
@badenbaden ааа я не понял, что Alarm - это выход. Вопрос снят!
О, ESP-07 - это чудесно, спасибо!

**Comment by badenbaden** [comment]
Единственное, есп07 точно имеет 512кб памяти, возможно есть на 1мб, а вот по второй картинке нужно узнавать. Это заморочки, если иметь возможность расширение функционала с большим объемом памяти.
По вопросу включения транзистором ЕСП - вопрос можно решить несколькими путями.
1. Оставить существующую схему питания от стандартного ватериуса и использовать модули нормального качества. Тогда и не будет получаться жор от 2 до 30 мкА, в зависимости от экземпляра модуля.
2. Можно стаб с выходом EN
3. Транзистором N-канальным (как я предлагаю) или Р-канальным (коммутация + питания)
4. Возможно еще что-то, до чего мы не додумались)))

Вопрос только в том, что утечка будет в любом случае, а вот где выгодней для нашего случая покажет только натурные испытания.

@OloloevReal - Приветствую! А где будет утечка? Земли на есп нет (при выключенном транзисторе, все входы подключены к +, линии данных SDA и SCL также подтянуты к +. Через что утекать будет. Схема ключа абсолютно рабочая, вот только не тестированная на питании контроллера.

**Comment by badenbaden** [comment]
Еще вопрос, а есп впадает в спячку или тини просто вырубает ее выводом EN? Если впадает в спячку, то в какой режим. Это я про оригинальный Ватериус.
И вообще, что мы можем выиграть, вырубая всю есп?

**Comment by OloloevReal** [comment]
@badenbaden 

> Приветствую! А где будет утечка? Земли на есп нет (при выключенном транзисторе, все входы подключены к +, линии данных SDA и SCL также подтянуты к +. Через что утекать будет. Схема ключа абсолютно рабочая, вот только не тестированная на питании контроллера.

Там же еще какие-то RX и TX есть, а есть еще пыль и влажность и еще куча необъяснимых явлений. По сути, если в документации не указанно что микроконтроллер так можно запитать, - значит нельзя. Давным давно пробовал через транзисторный ключ включать ESP, у меня не получилось, ESP зависала в непонятном состоянии. Разбираться почему это происходило не стал, может быть транзистор полностью не открывался, не знаю.
А чем вы собираетесь открыть мосфет, для него обычно 5 вольт нужно на затвор

**Comment by dontsovcmc** [comment]
1. Единственное, есп07 точно имеет 512кб памяти
- память только для ОТА нужна. 

2. Пути:
а. Оставить существующую схему питания от стандартного ватериуса и использовать модули нормального качества.
- В топку. Я тоже думал, что "ща мануал почитаю", перестанут есть. А когда через пин выключенной ЕСП течет 3мкА и никто на форуме не отвечает почему... Я не нашел объяснений, почему одни жрут мало, другие много. Это с одинаковой микрухой памяти происходит. Гадание не наш метод.

б. стаб с выходом EN
- Да, самый понятный вариант. Но электронщики могут шапками закидать. Плюс 20-30руб не играют роли. Однако, может быть проблема купить.
Можно даже Attiny без стаба подключать, а стаб только на ЕСП. Но тогда нужно делитель напряжения для i2c делать и вроде все. Надо уточнить, не сильно ли убегает частота attiny от напряжения. 

в. Транзистором N-канальным (как я предлагаю) или Р-канальным (коммутация + питания).
- Способ для настоящих ковбоев. Так в принципе и надо. Осталось сделать /найти схему.
А можете задать вопрос на форуме esp8266.ru ? 

3. А где будет утечка? 
- Я лишь добавлю, что attiny прекрасно работает если остаётся питание на пинах, а снимается с пина +5В. Т.е. внутри может быть что угодно.

4. Еще вопрос, а есп впадает в спячку или тини просто вырубает ее выводом EN? Если впадает в спячку, то в какой режим. Это я про оригинальный Ватериус. И вообще, что мы можем выиграть, вырубая всю есп?
- я вызываю deepsleep и вырубаю EN. deepsleep типа 20мкА, а EN это 0мкА. Как бы не так (. Мы выигрываем независимость от качества пайки и компонентов китайцев. Сейчас ЕСП жрет от 50 до 70% энергии вхолостую и это боооль.

5. А чем вы собираетесь открыть мосфет, для него обычно 5 вольт нужно на затвор
- я скинул примеры мосфетов которые открывают. насколько я помню, существуют от 2.5В, возможно это именно они.

**Comment by badenbaden** [comment]
> @badenbaden
> 
> > Приветствую! А где будет утечка? Земли на есп нет (при выключенном транзисторе, все входы подключены к +, линии данных SDA и SCL также подтянуты к +. Через что утекать будет. Схема ключа абсолютно рабочая, вот только не тестированная на питании контроллера.
> 
> Там же еще какие-то RX и TX есть, а есть еще пыль и влажность и еще куча необъяснимых явлений. По сути, если в документации не указанно что микроконтроллер так можно запитать, - значит нельзя. Давным давно пробовал через транзисторный ключ включать ESP, у меня не получилось, ESP зависала в непонятном состоянии. Разбираться почему это происходило не стал, может быть транзистор полностью не открывался, не знаю.
> А чем вы собираетесь открыть мосфет, для него обычно 5 вольт нужно на затвор

Пыли там точно не будет. Влажности по идее тоже. К ТХ подключен к светодиод (через который у ватериуса утекает 3 мкА, со слов @dontsovcmc)? но земли у него опять же нет.
Симуляцию в протеусе я выкладывал [тут] (https://github.com/dontsovcmc/waterius/issues/128#issuecomment-604642790)

**Comment by dontsovcmc** [comment]
@badenbaden я думаю надо в интернете найти решение задачи, оно должно быть. ESP надежнее отключать целиком, чтобы не связываться с китайскими заморочками ). И лучше, чтобы отключался плюс... )

**Comment by OloloevReal** [comment]
@badenbaden 

> У выбранного транзистора - Пороговое Напряжение Vgs 1.75В

У выбранного это какого? NVTR4503?

![image](https://user-images.githubusercontent.com/38255298/77848080-d0490400-71ca-11ea-8d43-2543d65d0a06.png)

Посчитайте симуляцию на эквивалентной нагрузке - ESP потребляет 200-300 мА. Боюсь что может быть существенное падение напряжения, а если питать от 3В то это уже ниже допустимого порога для ESP

**Comment by badenbaden** [comment]
@OloloevReal 
Вы абсолютно правы. Будет падение напряжение. Были мысли, что мои симуляции надо бы провести с адекватной нагрузкой, а не просто со светодиодом.
Но я поступил так. Переделал схему включения ESP на P-канальный мосфет. Из той же линейки, что и NVTR4503 (N канальный) есть транзистор NVTR4502 (P канальный). Параметры у них почти одинаковые и он нам также не подходит (хотя при напряжении от 5 вольт он должен работать нормально).
Симуляции хорошо, но испытания на настоящих детальках лучше. Купил в чип-дипе транзистор [Fairchild FDN306P](https://static.chipdip.ru/lib/002/DOC001002372.pdf). Хотел еще [Alpha & Omega AO3401A](https://static.chipdip.ru/lib/244/DOC001244348.pdf), но они их потеряли)).
В общем к испытаниям.
Тестовый стенд - питание 3,3в. (нет 3 вольтового стаба под руками, хотя мог бы и в дипе купить), транзистор FDN306P, Gate (Затвор) подключен к + через 2 последовательно включенных резистора 3,3к, Source (Исток) подключен к +, к Drain (Сток) подключена нагрузка в виде 4 параллельно включеных резисторов 39 ом (дополнительно, для индикации нагрузки, параллельно резисторам включен светодиод с резистором 39 ом), в разрыв плюсового провода от источника питания включен амперметр. Управление транзистором осуществляется путем притяжки Gate к земле через резистор 3,3к.

Фото стенда:
![photo_2020-03-29_22-09-45](https://user-images.githubusercontent.com/16225816/77858141-402aaf00-720a-11ea-84a8-d0223b5f16e5.jpg)

Потребление схемы при высоком уровне Gate (Затвор), Тестер в режиме измерения мкА:
![photo_2020-03-29_22-09-49](https://user-images.githubusercontent.com/16225816/77858159-5d5f7d80-720a-11ea-9c9d-917c22169328.jpg)

Потребление схемы при низком уровне Gate (Затвор), Тестер в режиме измерения А:
![photo_2020-03-29_22-09-53](https://user-images.githubusercontent.com/16225816/77858197-897afe80-720a-11ea-9e05-5a430789d97e.jpg)

Напряжение на источнике питания (без нагрузки):
![photo_2020-03-29_22-09-59](https://user-images.githubusercontent.com/16225816/77858224-c515c880-720a-11ea-9ad6-55f44c9c1664.jpg)

Напряжение на источнике питания (с нагрузкой 0,33А):
![photo_2020-03-29_22-10-02](https://user-images.githubusercontent.com/16225816/77858245-e080d380-720a-11ea-82f6-45515029f2d9.jpg)

Напряжение на нагрузке (параллельно включенные резисторы):
![photo_2020-03-29_22-10-05](https://user-images.githubusercontent.com/16225816/77858269-0e661800-720b-11ea-83eb-7c045f435b51.jpg)

Падение напряжение на тестере в режиме Амперметра:
![photo_2020-03-29_22-10-09](https://user-images.githubusercontent.com/16225816/77858290-38b7d580-720b-11ea-9d22-98ef6b7572f3.jpg)

Если посчитать сумму 2.86 и 0.15 , то получается более 3 вольт. Но напряжение питания 3.3 в.
Также, если нагрузка будет не такой большой, а в подавляющем большинстве случаев так и будет (ЕСП кажется потребляет импульсно), то напряжение просядет еще меньше.
Ну и погрешность моих простейших приборов никто не отменял. Хотел проверить на реальной есп, но дома не оказалось.
Как то так.

**Comment by badenbaden** [comment]
Обновленная схема выглядит пока так.

![Schematic_Water-count-v2_attiny84_20200329214937](https://user-images.githubusercontent.com/16225816/77858528-d7910180-720c-11ea-8e6b-a95068f21060.png)

**Comment by dontsovcmc** [comment]
@badenbaden вы в Москве? напишите мне в телеграм

**Comment by dontsovcmc** [comment]
@badenbaden ошибка в порту прошивки attiny:  waterleak2 (PA5) нужен пин, а не waterleak1. 
https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/extras/ATtiny_x4.md

**Comment by badenbaden** [comment]
> @badenbaden вы в Москве? напишите мне в телеграм

> 
В личку или группу? Да, я в Москве.

**Comment by badenbaden** [comment]
> ошибка в порту прошивки attiny: waterleak2 (PA5) нужен пин, а не waterleak1.

> 
Вот это не понял. waterleak1 и waterleak2 это 2 независимых входа для 2х датчиков протечки. Оба порта ADC. Что не так?

**Comment by dontsovcmc** [comment]
@badenbaden в личку.
вы вытащили 6 пинов для прошивки тиньки. но в них нет PA5. вместо него PA7.

**Comment by badenbaden** [comment]
Теперь понял)) Это я поменял их местами, для лучшей разводки, а в порту забыл.

**Comment by badenbaden** [comment]
Продолжение экспериментов.
Т.к. нет в наличии [MCP1700T-3002E](https://static.chipdip.ru/lib/264/DOC005264291.pdf), то решил запитать через DC-DC. Настроил выход на 2,96 вольт (специально чуть ниже требуемых), согласно моих тестеров. В качестве нагрузки подключил ESP8266 модель 12. Прошил прошивку ESPEasy. 

Общий вид (квадратный вольтметр занижает показания на 2-3 сотки, отображает напряжение после dc-dc):
![photo_2020-03-31_14-46-58](https://user-images.githubusercontent.com/16225816/78023128-c6f0a080-735e-11ea-97d5-b2c51c33acce.jpg)

ЕСП с резисторами, соплями и проводами:
![photo_2020-03-31_14-47-02](https://user-images.githubusercontent.com/16225816/78023147-cfe17200-735e-11ea-95c3-b3dd4035d132.jpg)

Стенд по крупнее:
![photo_2020-03-31_14-47-06](https://user-images.githubusercontent.com/16225816/78023158-d53ebc80-735e-11ea-960b-6fda6e10b83d.jpg)

ЕСП надо бы нагрузить. На сколько смог нагрузил ее разными отправками данных по HTTP и MQTT, синхронизацией времени, опросом датчиков и т.д. В общем как умел)) Ниже кусок лога есп через web интерфейс:
![photo_2020-03-31_14-47-19](https://user-images.githubusercontent.com/16225816/78023186-e7205f80-735e-11ea-8cef-9dd75105b491.jpg)

Тут главная ESPEasy. Видно, что нагрузка 100%, это конечно нагрузка наверняка процессора, но тоже важно.
![photo_2020-03-31_14-47-26](https://user-images.githubusercontent.com/16225816/78023193-ec7daa00-735e-11ea-9d47-1a76b6231614.jpg)

При всех моих манипуляциях напряжение питания не изменялось, проверить потребление в любом состоянии я не смог. Мой тестер с падением напряжения на проводах не дал мне этого сделать - показывал 196-198 мА потребления, но есп не стартовала. Вообще заметил, что все эти китайские провода и макетки очень сильно вносят погрешность на таких низких напряжениях. На физической плате из-за пайки и малого размера между элементами такого не будет наблюдаться.

Результаты:
При питании от 3 вольт и использовании транзистора FDN306P в качестве ключа ЕСП работает стабильно. Думаю что питание через MCP1700 не внесет никаких корректив.

**Comment by badenbaden** [comment]
Несколько рендеров разведенной платы.

![waterius-3D](https://user-images.githubusercontent.com/16225816/78138278-58c7de80-742f-11ea-8b54-0b7ff31513a6.png)

![waterius-3D-1](https://user-images.githubusercontent.com/16225816/78138299-5d8c9280-742f-11ea-9811-2f2357bb84c7.png)

![waterius-3D-2](https://user-images.githubusercontent.com/16225816/78138319-62514680-742f-11ea-933b-6b6d4e293d9c.png)

**Comment by dontsovcmc** [comment]
@badenbaden вкуснота то какая! =) 
p.s. не вижу габариты: а кнопка и светодиоды напротив дырок под вводы на корпусе?

**Comment by OloloevReal** [comment]
@badenbaden на заметку, вдруг пригодится мой опыт
Вполне удачно получилось разместить индикацию и кнопку управления в резиновых заглушках распредкоробки

![IMG_7869](https://user-images.githubusercontent.com/38255298/78151839-aea58200-7441-11ea-9a3d-e6f23f8ee8c4.JPG)

**Comment by badenbaden** [comment]
габариты платы 73х73.

Кнопка так изначально и планировалась - без прорезания отверстий.
Светодиоды смотрят в верх, через кабельные вводы. И как я и говорил - они сами у этой коробки работают как сальник. Но для верности герметиком можно промазать.
Вот скрины в корпусе.

![render1](https://user-images.githubusercontent.com/16225816/78152514-92eeab80-7442-11ea-81bb-b15bc1cd0f52.jpg)


![render2](https://user-images.githubusercontent.com/16225816/78152529-984bf600-7442-11ea-91a5-48b2066539ad.jpg)

Тут "вскрыл" заднюю часть коробки:
![render3](https://user-images.githubusercontent.com/16225816/78152537-9d10aa00-7442-11ea-917e-4103089d9cb1.jpg)

**Comment by OloloevReal** [comment]
@badenbaden а в чем смысл тогда использовать Г образную кнопку?

**Comment by badenbaden** [comment]
> а в чем смысл тогда использовать Г образную кнопку?

> 
Как в чем? Плата расположена в другой плоскости относительно кабельного ввода. Потому то и "Г" образная. Можно поставить стандартную, но чтоб ее нажать нужно будет вскрывать крышку.

**Comment by OloloevReal** [comment]
@badenbaden 

`Кнопка так изначально и планировалась - без прорезания отверстий.`

А как без отверстия на нее нажимать тогда?

**Comment by badenbaden** [comment]
Длина штыря кнопки подобрана так, что он упирается в центр кабельного ввода. Коробка сделана методом двойной экструзии - корпус жесткий, а кабельные вводы из мягкого материала, похожего на резину. Нажатие снаружи вызывает продавливание кабельного ввода, который и нажимает на кнопку. Отверстие не нужно, все герметично.
Вот [видео](https://www.youtube.com/watch?v=Hu_ML8vEduI) об этой коробке.

**Comment by badenbaden** [comment]
Можно уже заказать платы и компоненты. Только вот дойдут ли? Везде все перекрывают блин.

**Comment by dontsovcmc** [comment]
@badenbaden а сколько потребляет поддержание HIGH на полевом транзисторе? Он ведь в таком виде должен спать, верно?

**Comment by badenbaden** [comment]
@dontsovcmc Вот [тут](https://github.com/dontsovcmc/waterius/issues/128#issuecomment-605686931) фото и описание моего первого теста. Мой тестер показывает 00.0 в режиме измерения до 200 мкА. Получается что менее 1 десятой микроампера. 

![datasheet](https://user-images.githubusercontent.com/16225816/78162728-f3d0b080-744f-11ea-96e1-26fb3a09f888.png)

**Comment by badenbaden** [comment]
Вот к чему мы пришли - [https://github.com/badenbaden/Waterius-Attiny84-ESP12F](https://github.com/badenbaden/Waterius-Attiny84-ESP12F)

На текущий момент платы заказаны. По прибытию начнем тестирование.

**Comment by SergeiSOficial** [comment]
MCP1700 выдет максимум 250мА. Для ESP32 рекомендуют источник питания на 500мА. 
Рекомендую сделать фильтры по питанию между +3V и +3V-ESP. [BLM31](https://ru.mouser.com/Search/Refine?Keyword=BLM31) и конденсаторы.
 Т.к. во время включения или работы ESP мы получем очень много шумов.

**Comment by badenbaden** [comment]
Не совсем понял, что значит между +3V и +3V-ESP?
В оригинальной версии этот стаб прекрасно тянет есп. И у нас не есп32 а есп8266.

**Comment by SergeiSOficial** [comment]
пример:
![image](https://user-images.githubusercontent.com/30231940/78557440-79ba7600-7819-11ea-9cd5-d6c30d2b73ee.png)
Еще часто разделяют аналоговую часть и цифровую. Часто разделают полигоны земли. [Пример](http://radiostorage.net/1026-podsistema-pitaniya-v-mikrokontrollere.html)
[Пример](https://studfile.net/preview/7611260/page:9/)

**Comment by SergeiSOficial** [comment]
В пике ESP8266 тоже потребляет в пике до 500мА

**Comment by badenbaden** [comment]
@SergeiSOficial Вы все правильно пишите. Только это прототип. потребуются дополнительные элементы-добавим, будут помехи - разделим. Да и не для военной промышленности мы разрабатываем)). А по поводу потребления в 500 мА - что-то более сотни устройств с есп и таким стабом работают очень и очень давно.
Все схемы и разводка в открытом доступе. Конструктивные предложения приветствуются.

**Comment by dontsovcmc** [comment]
@SergeiSOficial огромное спасибо за комментарий!
Ого, а чем эти фильтры отличаются от smd дросселей-катушей которые можно часто встретить на питании?

Такой фильтр можно еще на все входы от счетчиков поставить?

MCP1700 держит пики превышающие 250мА. Если не хватит, другой стаб поставим. У тебя есть на примете?
Я вот тут выписываю https://github.com/dontsovcmc/waterius/issues/3#issuecomment-380848998

**Comment by SergeiSOficial** [comment]
Эти фильтры настроены таким образом, чтобы гастить ВЧ помехи и не мешать пстоянному току. Там есть разные частотные характеристики. Можно ставить на входы от счетчиков.
Относительно дросселей они похожи. Разница в частотных харакетристиках и в величине индуктивности. Дроссели по питанию часто применяются для выпрямления и стабилизации токов, но для ВЧ помех они бывают слабы.

**Comment by dontsovcmc** [comment]
Тема переросла в отдельную модификацию Ватериуса, закрываю. Все обсуждения ее в другом репозитории.
https://github.com/badenbaden/Waterius-Attiny84-ESP12F

**Comment by Kabron287** [comment]
Я не понимаю, что вы так мучаетесь с ключами питания. Есть годами проверенная схема питания в транзисторном тестере Маркуса. 
Работает безупречно.

**Comment by dontsovcmc** [comment]
> Я не понимаю, что вы так мучаетесь с ключами питания. Есть годами и тысячами реализаций проверенная схема питания в транзисторном тестере Маркуса.
> Работает безупречно.

А можете привести ссылку? Спасибо!

**Comment by Kabron287** [comment]
Классика в общем:
https://vrtp.ru/index.php?s=d7e4167b0d2c188d8f231b518dcebeee&showtopic=25020&st=0&#entry598223

**Comment by Giperson400** [comment]
Здравствуйте! Подскажите пожалуйста сей девайс работает как полагается, но кроме датчиков протечки? Появилось желание реализовать сбор данных с 4х счетчиков и поэтому интересуюсь.

**Comment by badenbaden** [comment]
Приветствую! Да, все 4 канала работают и передаются данные, но на сайте ватериуса есть поддержка только 2х каналов. Датчики протечки тоже работают, но не так как хотелось бы.

**Comment by Giperson400** [comment]
badenbaden, а можно в случае вопросов написать на вашу электронную почту ?

**Comment by badenbaden** [comment]
Можно

**Comment by Giperson400** [comment]
А какой адрес электронной почты? В профиле у вас видимо скрыт.

**Comment by badenbaden** [comment]
badaevde@gmail.com

**Comment by Giperson400** [comment]
Спасибо

**Comment by maks2689** [comment]
Очень понравился проект, но как я понял обновлений прошивки тини не предвидится

**Comment by dontsovcmc** [comment]
К сожалению, не хватает ресурсов для развития =(.
