### ISSUE TITLE
Чтение напряжения питания с батареек аналоговым входом ESP

### ISSUE THREAD

**Issue by OloloevReal** [dontsovcmc/waterius#139]
Добрый день!

Для ESP32 замер напряжения с элементов питания (4xAA или 1x18650) делал следующим образом:

![image](https://user-images.githubusercontent.com/38255298/85840097-95904100-b7a4-11ea-9807-d12afe470bd8.png)

Где:
VBAT  - выход элементов питания
GPIO-13 - Выход ESP разрешающий замер
GPIO-27 - Аналоговый вход ESP

Т.к. напряжение снимается с делителя 50/50, то АЦП считывает значение эквивалентное половине VBAT

![2020-06-26_11-52-59](https://user-images.githubusercontent.com/38255298/85840460-29faa380-b7a5-11ea-8317-f54108686b56.png)

Цель всей этой схемотехники избежать постоянной утечки на землю, и делать замер только по запросу.
Необходимы конечно свободные IO, с ESP32 с этим все в порядке, а вот ESP8266 дефицит
Может пригодится

**Comment by dontsovcmc** [comment]
Мне Иван рисовал похожую схему:
![photo_2020-06-26_12-54-44](https://user-images.githubusercontent.com/6192152/85845002-3d5d3d00-b7ac-11ea-8bd0-ecf864950d13.jpg)

Дмитрий ее реализовал на большой плате:
![Screenshot_6](https://user-images.githubusercontent.com/6192152/85845404-dee48e80-b7ac-11ea-8d4a-e49cac5c9145.png)

На текущий ватериус не ясно, куда ее запихнуть =( А вот на ESP-12F влезает.

**Comment by OloloevReal** [comment]
Так-то тоже самое, только на полевиках. С ESP01, если правильно помню, только один ADC и тот не распаян, вариант только подпаиваться к чипу.  И попасть в диапазон от 0 до 1.0 V придется
