### ISSUE TITLE
Добавить настройку периода отправки

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#144]
ESP8266 
1.1. Добавить в дополнительные настройки wifiManger поле “Как часто обновлять данные о показаниях, мин.” Значение по умолчанию: 1440 (1 день). Для инициализации использовать константу WAKE_EVERY_MIN. 
1.2. Добавить в структуру настроек параметр short wakeup_period_min, отвечающий за период отправки данных. 
1.3.  Добавить передачу данных по I2C от ESP Attiny сразу после инициализации. Используемые поля: ID команды, данные(период), CRC. 

Attiny85 
1.4.  Добавить прием данных по I2C с использованием ID команды из п. 1.3. Осуществить проверку CRC. 
1.5. Добавить сохранение периода отправки в EEPROM, а также чтение при начальной инициализации. 
1.6. Использовать заданное значение периода отправки для пробуждения ESP.

**Comment by obrianw** [comment]
Нужный параметр, особенно когда есть Умный дом. 👍

**Comment by dontsovcmc** [comment]
> Нужный параметр, особенно когда есть Умный дом. 👍
> Понятно, что при увеличении передачи данных (будим ESP8266, wifi, согласование) потребуется сменить на более мощные аккумуляторы или ставить БП.

У меня проработал около 2-х лет при передачи каждые 30 сек.

**Comment by obrianw** [comment]
> > Нужный параметр, особенно когда есть Умный дом. +1
> > Понятно, что при увеличении передачи данных (будим ESP8266, wifi, согласование) потребуется сменить на более мощные аккумуляторы или ставить БП.
> 
> У меня проработал около 2-х лет при передачи каждые 30 сек.

Не ожиданно! Это же меняет всё (!) Так часто это конечно сильно, но для проверки начальных показаний самое-то!

И значит не зря, что затеял собрать себе таких три штуки, и даже по Вашему шаблону из гайда таки заказал с десяток плат (3-ей версии :) ) на PCBWay (использовав скидку на первый заказ) оплатив только доставку и комиссию за оплату (1$ комиссии с $5 это конечно сильно, но что-ж возьмешь с банков, ещё те крахоборы) и опять же по Вашему списку так же заказал недостающие компоненты, коих нет под рукой... 
Огромное спасибо за такой подробный и открытый проект!

**Comment by dontsovcmc** [comment]
Заголовок поля: "Как часто обновлять данные о показаниях, мин"

**Comment by dontsovcmc** [comment]
Можно задать период выхода на связь в минутах. По умолчанию 1 сутки (1440 мин). Период хранится в памяти ESP. При каждом пробуждении она передает в attiny это значение.
