### ISSUE TITLE
Как проапгрейдить софт на плате ранней ревизии?

### ISSUE THREAD

**Issue by simak-alexandr** [dontsovcmc/waterius#148]
Добрый день!

Мне достался Waterius в начале августа 2018, тот самый с немного сколотой коробочкой. 
Устройство до сих пор служит верой и правдой еще от родного комплекта батареек, перебоев в передаче показаний не было, @dontsovcmc Спасибо! 

Сейчас меняем счётчики, и пока устройство не используется, хочу уточнить, можно ли как-то плюс-минус быстро безболезненно накатить на это раннее устройство новую прошивку и начать жить с прелестями личного кабинета на https://waterius.ru/ и другими полезностями?

**Comment by dontsovcmc** [comment]
Спасибо за поддержку проекта! Это очень помогло в первых шагах!
Надо обновить обе прошивки. Это можно сделать установив софт и использую программатор (или плату Ардуино).
