### ISSUE TITLE
Безбожно завышает по горячему каналу

### ISSUE THREAD

**Issue by Kabron287** [dontsovcmc/waterius#150]
В 4 раза.
Дребезг?

**Comment by dontsovcmc** [comment]
Хм... может плохой контакт (провод в пыли или не закрепили в разъеме) ?
От дребезга надежная софтовая защита...

**Comment by Kabron287** [comment]
Да ладно! Барабашка гораздо вероятнее.
Там вроде в настройках коэффициент можно подкрутить?
Ибо, холодная тоже не идеальна.
![Water](https://user-images.githubusercontent.com/2493191/107137062-e1e65680-6919-11eb-8c43-3aa073f640ac.jpg)

**Comment by OloloevReal** [comment]
@Kabron287 а вы с разводкой не напутали? У валтека видел счетчики с комбинированным выходом - и сухой контакт и namur.

**Comment by Kabron287** [comment]
Т.е. я типа два провода местами перепутал?

**Comment by dontsovcmc** [comment]
@Kabron287 Очень странно себя ведет. С Valtek Ватериус работает, но обычно у них 4 проводка, а у вас 2. Пришлите свою почту на contact@waterius.ru, посмотрим графики.

**Comment by dontsovcmc** [comment]
@Kabron287 "Там вроде в настройках коэффициент можно подкрутить?" - счетчики либо 1л/имп, либо 10л/имп. Если ваш на 1л и вы не вылили 3л холодной воды во время настройки, то потребление должно ровно в 10 раз быть выше.
Я думаю будет правильно вам проверить импульсный выход тестером - измерьте сопротивление при открытой воде.

**Comment by Kabron287** [comment]
Как раз пришел OWON BT41+.
Повешу в режиме логгера на выходных.
