### ISSUE TITLE
Прошитая attiny85-20SUR есть 250мкА

### ISSUE THREAD

**Issue by dominionish** [dontsovcmc/waterius#158]
Всем привет!
Понравилась задумка, поставил счетчики с проводами и решил сваять сам cей девайс.
Плату сделал посредством ЛУТ, все вроде по технологии и по вашей инструкции
Прошил контроллер и проверив ток, оказалось что он кушает 250мкА. Что в 25 раз больше заявленного в вашей инструкции (7-10мкА).
Плату отмывал от флюса с помощью средства flux off, затем промывал в воде и вымчивал в спирте, чтобы вода вытеснилась
Не помогло.
Может ли быть дело еще в чем то? Я так понимаю ЛУТ - это самая первая версия платы. ИЛи не важна версия, ток будет 7-10 мкА в любом случае?
Вобщем буду рад любым советам.
Вот кстати фото платы, сделанной моими не очень прямыми руками. Но все правильно, проверял 10 раз по схеме:
![1](https://user-images.githubusercontent.com/8955774/110022421-b8b8ba80-7d4d-11eb-9448-d41ad7962e0a.jpg)
![2](https://user-images.githubusercontent.com/8955774/110022431-ba827e00-7d4d-11eb-85fe-bd1e9d568167.jpg)

**Comment by dominionish** [comment]
Вобщем пока я это писал, плата сушилась уже от второй промывки средством Flux Off. После того как средство испарилось мультиметр показал потребление тока в 8-14 мкА. Что в принципе соответствует заявленному. Поэтому issue можно закрывать. 
И спасибо за такой крутой проект и за подробное описание с инструкцией!

**Comment by dontsovcmc** [comment]
Отличная вышла плата!
Да, после прошивки должно быть около 10мкА (прыгает, т.к. измерения идут). Часто из-за флюса повышенное потребление. Проверьте еще после суток работы!
Спасибо за отзыв!
