### ISSUE TITLE
Доработки платы

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#159]
1. увеличить площадки под Attiny
2. увеличить толщину дорожек питания, убрать переходы между слоями в дорожках питания
3. 
4. версия 4.0

...

**Comment by foxel** [comment]
Мог бы посоветовать зацепить заливку на bottom к GND и, возможно, на top к +3

**Comment by dontsovcmc** [comment]
Пока других доработок нет, закрою.
