### ISSUE TITLE
Индикация светодиода при считывании импульсов

### ISSUE THREAD

**Issue by radiokilcat** [dontsovcmc/waterius#16]
Предлагаю добавить индикацию светодиода в момент получения устройством импульса. 
Для экономии энергии можно включать индикацию только в "настроечном" режиме, например, во время включенной точки доступа, так как примерно в это время пользователь настраивает устройство.

**Comment by dontsovcmc** [comment]
Мне кажется это может решить проблему: https://github.com/dontsovcmc/waterius/issues/18
Подключил, пролил, нажал кнопку - увидел изменения.

**Comment by dontsovcmc** [comment]
чтобы не усложнять код, ограничимся решением #18
