### ISSUE TITLE
Доработка под электромагнитные индукционные счетчики

### ISSUE THREAD

**Issue by maijye** [dontsovcmc/waterius#163]
Здравствуйте! Возможно ли доработать эту плату (сделать 5-й выход) под счетчики/расходомеры, с 3 проводами.
Красный - питание+ (12в)
Черный - питание-
Желтый - электрические импульсы 5v по 10-15мА 

![image](https://user-images.githubusercontent.com/75762350/111300802-874fc100-8662-11eb-9da2-c9c74ec3d558.jpeg)

![image](https://user-images.githubusercontent.com/75762350/111300902-a3ebf900-8662-11eb-8b6c-8b275420e278.jpeg)

**Comment by dontsovcmc** [comment]
Это хорошая задачка.
Программно: 
1. требуется добавить подсчет импульсов по прерыванию.
2. PULLUP входов всегда включен.

**Comment by maijye** [comment]
> Это хорошая задачка.
> 
> Программно: 
> 
> 1. требуется добавить подсчет импульсов по прерыванию.
> 
> 2. PULLUP входов всегда включен.
> 
> 
> 
> 

Как Вы думаете, намного ли этот 5-й выход может увеличить потребление энергии?
Есть разные счетчики, примерно от 20 до 10000 импульсов/литр.


Есть счетчики для таких приборов с экраном. Работают от батареек.
![image](https://user-images.githubusercontent.com/75762350/111390487-dd088580-86c3-11eb-9a27-f2cd733c33a6.jpeg)

![image](https://user-images.githubusercontent.com/75762350/111390507-e5f95700-86c3-11eb-86b1-ba59c31ef358.jpeg)

**Comment by dontsovcmc** [comment]
Не увеличит потребление никак. 

3. Переделать буфер, сохраняющий каждый импульс в eeprom в то, чтобы он сохранял, скажем каждый литр.
4. Добавить вес импульса в ESP.

**Comment by maijye** [comment]
> Не увеличит потребление никак. 
> 
> 
> 
> 3. Переделать буфер, сохраняющий каждый импульс в eeprom в то, чтобы он сохранял, скажем каждый литр.
> 
> 4. Добавить вес импульса в ESP.

По-хорошему, нужно сначала через счетчик прокачивать литр воды, а в метрике указывать, что - вот, это был ровно литр. А в метрике будет фиксироваться, что в 1 литре тестовом 577 импульсов например.

Мало того, что все эти счетчики сильно отличаются по количеству импульсов/литр, так еще и каждый счетчик одной модели может иметь индивидуальные отклонения. Например, по тех. характеристикам должно быть 30 литров/литр, а реально эти счетчики дают по-разному 27-35 импульсов/литр.

**Comment by dontsovcmc** [comment]
@maijye вау жесть =(. вообще интерфейс ватериуса позволяет реализовать градуировку легко - веб морда получает информацию от attiny о кол-ве импульсов. 
Но к сожалению задача специфическая, поэтому закрою тему. Хотя многие спрашивают про расходомеры, но я не подозревал про необходимость градуировки =(. Теперь буду знать.
