### ISSUE TITLE
Регулярная отправка актуальных данных через MQTT

### ISSUE THREAD

**Issue by YaLiC** [dontsovcmc/waterius#171]
Ваше устройство, на сегодняшний день, наиболее пригодное для домашнего учёта воды и дружественное к пользователю. Альтернативы либо ущербны по функционалу и стоят не адекватных денег, либо требуют глубоких практических навыков для самостоятельного изготовления. И за это хочу поблагодарить! У Вашей разработки перспективное будущее.
Я понимаю, что ничего абсолютно универсального не существует. Однако, имея уже существующий функционал, я уверен, что посредством настроек, можно получить желаемое....
Ватериус, конкретно для меня, нужен для контроля потребления воды в режиме реального времени. Иными словами отправка данных должна быть не реже 1-го раза в минуту. На сколько это возможно, что для этого нужно сделать?

**Comment by dontsovcmc** [comment]
Приветствую! Огромное спасибо за отзыв! Будем рады его видеть в соцсетях или сайтов с отзывами.

ответ: с версии 0.10.1 появилась возможность менять интервал отправки данных. Последняя версия 0.10.3 берите ее
