### ISSUE TITLE
Значение некоторых топиков MQTT

### ISSUE THREAD

**Issue by ivakorin** [dontsovcmc/waterius#172]
Подскажите пожалуйста значения топиков MQTT:
**impX** - количество импульсов? 
**f**  -литров на импульс? 
**waketime** - время последней активности в секундах? 
**setuptime** - время затраченное на последнюю установку в секундах? 
**adcX**
**good**
**version** - версия устройства?

**Comment by dontsovcmc** [comment]
Добрый день! Вот описание https://github.com/dontsovcmc/waterius/blob/master/Export.md

**Comment by ivakorin** [comment]
Спасибо!
