### ISSUE TITLE
Переименовать Ватериус в роутерах

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#177]
Кажется Ватериус определяется роутером как «ESPxxxx». Нужно сделать чтобы роутер его определял как «Waterius-xxxxx», где хххх - chip id.

**Comment by neitri** [comment]
Нужно копать в сторону wifi.hostname("имя сети")

**Comment by dontsovcmc** [comment]
Огонь, спасибо!
WiFi.hostname("relay");
WiFi.begin(ssid, password);

**Comment by dontsovcmc** [comment]
@neitri вы добавил установку hostname уже после подключения к роутеру, думаю нужно ее ставить перед: WiFi.begin();
(у вас может работать так, т.к. достаточно 1 раз установить и esp8266 будет использовать это имя впредь)

**Comment by neitri** [comment]
Пробовал и в setup и вначале loop. Неработало. Только после соединения заработало. До соединения даже имя не возвращает, пустая строка приходит.

**Comment by dontsovcmc** [comment]
done
