### ISSUE TITLE
Изменение настроек - нужно ли заново проливать воду?

### ISSUE THREAD

**Issue by Nixellion** [dontsovcmc/waterius#179]
Если, например, хочется поменять частоту отправки показаний на локальный сервер - можно опять активировать режим настройки, старые настройки вроде сохраняются, в целом ок. Но вот что совершенно не очевидно - нужно ли заново проливать горячую и холодную воду?

**Comment by dontsovcmc** [comment]
С версии 0.10.2 не нужно. До — нужно с вероятностью 10%...
