### ISSUE TITLE
Измерение напряжения батареи средствами ESP

### ISSUE THREAD

**Issue by neitri** [dontsovcmc/waterius#186]
В ESP имеется возможность измерять напряжение питания. ESP.getVcc(). Можно использовать встроенные средства вместо чтения из ATTiny.

**Comment by dontsovcmc** [comment]
Плюсы: 
- уменьшение кода в attiny.
- отсутствие периодического опроса в момент подключения к WiFi.

**Comment by dontsovcmc** [comment]
Спасибо, @neitri
