### ISSUE TITLE
Добавить флаг отправка по кнопке

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#190]
Хочется явно видеть, что отправка была по кнопке, а не автоматическая

**Comment by neitri** [comment]
Предлагаю вариант.
#define TRANSMIT_MODE_MANUAL 3
и сам mode включить в отправку.

**Comment by dontsovcmc** [comment]
А не достаточно ли будет wdt_count == 0?

**Comment by neitri** [comment]
В esp сейчас он не передается. Нужно изменить оба контроллера. Поэтому на мой взгляд mode проще расширить, чем добавлять wdt_count

**Comment by neitri** [comment]
В #211 добавил mode MANUAL_TRANSMIT_MODE, также добавил атрибут в json mode.

**Comment by dontsovcmc** [comment]
Спасибо, @neitri
