### ISSUE TITLE
Спустя какое то время перестает подключаться к WiFi и передавать показания

### ISSUE THREAD

**Issue by Nixellion** [dontsovcmc/waterius#204]
Здравствуйте, 

Пользуюсь Waterius полгода-год и с самого начала есть такая проблема: спустя какое то время, от нескольких дней до месяца waterius перестает подключаться к WiFi и передавать показания. При этом достаточно зажать кнопку на пару секунд, он подключается, передает показания накопленные за все время что он их не передавал разом, и продолжает работать.

Проблема решается легко, но все таки кажется что это может быть проблема в прошивке. Допускаю что может быть не достаточно стабильный уровень WiFi в месте где находится устройство, но почему после неудачной попытки подключения он, как будто, перестает пытаться подключаться? Или где то что то подвисает в ESP? 

Сталкивались ли уже с такой проблемой?

Спасибо

**Comment by dontsovcmc** [comment]
@Nixellion Добрый день! Пришлите в телеграм dontsovcmc ваш адрес почты, я посмотрю, какая версия прошивки у вас.
В 21й версии attiny мы сделали аварийную перезагрузку при зависании. Но зависания были замечены в 0.10.1... У вас есть возможность обновиться на последнюю версию?
Есть ещё гипотеза - если меняется канал wi-fi, то Ватериус дольше подключается.
