### ISSUE TITLE
Режим настройки отключается через 40 секунд.

### ISSUE THREAD

**Issue by KBurdin** [dontsovcmc/waterius#225]
Имеется самодельный Ватериус (сделан в 2019 году). 
После обновления прошивки на 24 версию режим настройки отключается через 40 секунд.

**Comment by OloloevReal** [comment]
А фьюзы у вас для Attiny верно прошиты?

**Comment by KBurdin** [comment]
Про фьюзы не подумал. Работы с AVR опыта практически не имею. В итоге попробовал откатиться обратно на 9 версию - тоже самое. 40 секунд и выключилась... Перекинул другую  attiny - все завелось.
