### ISSUE TITLE
Добавить настройку параметра retained для mqtt параметров

### ISSUE THREAD

**Issue by Spirituss** [dontsovcmc/waterius#234]
Просьба добавить настройку параметра retained для mqtt параметров для возможности автоматического обновления значений в УД.

**Comment by dontsovcmc** [comment]
Добрый день! А в каких случаях требуется retained=false? Сейчас он всегда true.

**Comment by Spirituss** [comment]
> Добрый день! А в каких случаях требуется retained=false? Сейчас он всегда true.

Не знаю по какой причине, но у меня сейчас все сообщения в топике с false

**Comment by dontsovcmc** [comment]
> > Добрый день! А в каких случаях требуется retained=false? Сейчас он всегда true.
> 
> Не знаю по какой причине, но у меня сейчас все сообщения в топике с false

Задайте вопрос в телеграм чате waterius_forum ... В коде true: https://github.com/dontsovcmc/waterius/blob/master/ESP8266/src/sender_mqtt.h#L40
