### ISSUE TITLE
Отображать 3 знака после запятой в личном кабинете

### ISSUE THREAD

**Issue by Spirituss** [dontsovcmc/waterius#235]
Сейчас нет возможности в режиме реального времени делать сверку показаний в MQTT и в личном кабинете. В MQTT показания с 3 знаками, в личном кабинете - округление. Приходится долго ждать, чтобы понять, есть ли расхождение.

**Comment by dontsovcmc** [comment]
В MQTT и личный кабинет отправляются одинаковые числа, зачем их сравнивать? =)

**Comment by neitri** [comment]
А можно уточнить цену импульса на ваших счетчиках?
Предполагаю что 10 литров, 0.01м³.

**Comment by Spirituss** [comment]
> А можно уточнить цену импульса на ваших счетчиках? Предполагаю что 10 литров, 0.01м³.

10 литров. Но вопрос не в этом, а в том, что если округляем - то в обоих местах, если нет - то так же, в обоих показываем как есть. В ватериус начальные показания вносил 3 знака, там так 3 знака и сохраняются.

**Comment by neitri** [comment]
Для отображения 3го знака после запятой необходимы счетчики с весом импульса в 1 литр на импульс. При цене в 10 литров, 3й знак будет всегда 0.

**Comment by dontsovcmc** [comment]
> > А можно уточнить цену импульса на ваших счетчиках? Предполагаю что 10 литров, 0.01м³.
> 
> 10 литров. Но вопрос не в этом, а в том, что если округляем - то в обоих местах, если нет - то так же, в обоих показываем как есть. В ватериус начальные показания вносил 3 знака, там так 3 знака и сохраняются.

Идея в том, что личный кабинет - он для обычного пользователя. Нет потребности в 3х знаках после запятой.
А MQTT вы вольны настраивать, как вам хочется - с 2, 3 знаками. Поэтому смешивать не имеет смысла. Предлагаю закрыть задачу =)

**Comment by Spirituss** [comment]
> > > А можно уточнить цену импульса на ваших счетчиках? Предполагаю что 10 литров, 0.01м³.
> > 
> > 
> > 10 литров. Но вопрос не в этом, а в том, что если округляем - то в обоих местах, если нет - то так же, в обоих показываем как есть. В ватериус начальные показания вносил 3 знака, там так 3 знака и сохраняются.
> 
> Идея в том, что личный кабинет - он для обычного пользователя. Нет потребности в 3х знаках после запятой. А MQTT вы вольны настраивать, как вам хочется - с 2, 3 знаками. Поэтому смешивать не имеет смысла. Предлагаю закрыть задачу =)

Решил задачу другим способом - в ха сенсор сделал с 2 знаками + в ватериус в качестве стартовых данных указал тоже 2 знака.
