### ISSUE TITLE
Сбой периода пробуждения

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#242]
<img width="309" alt="Снимок экрана 2022-12-21 в 19 34 46" src="https://user-images.githubusercontent.com/6192152/208917607-4edccdbc-e5d4-47c9-ac7f-531f218fa100.png">

Стоит 60 минут, потом почему то раз в 15 мин начал отправлять.

Не очень понятно, как отлаживать.

Ещё любопытно, как на расчёты повлияет не получение точного времени по NTP...

**Comment by neitri** [comment]
Без синхронизации времени не имеет смысла изменение #209 
Пересчет периода необходимо делать только при работающей синхронизации времени. Само просто наверно повторно попытаться синхронизировать время. 
                
```
//Перерасчет времени пробуждения
if (mode == TRANSMIT_MODE) { 
```
изменить на 
```
//Перерасчет времени пробуждения
if (mode == TRANSMIT_MODE && setClock()) {
```

**Comment by dontsovcmc** [comment]
Да, подумал про это...

Ещё вопрос:
1. Что вернёт time(nullptr), если не будет синхронизировано время?
2. Может сделать, если время не синхронизировано, то не выполняем уточнение периода, а оставляем константу?
3. При каких обстоятельствах t1 <= 1?

```
time_t now = time(nullptr);
  time_t t1 = (now - sett.last_send) / 60;
  if (t1 > 1 && data.version >= 24)
                    
```

**Comment by neitri** [comment]
Если период отправки минуту поставить, то может получится t1=0 а это не хорошо будет.

**Comment by dontsovcmc** [comment]
Да, в прошивке Tasmota определяется константа, если время ниже ее, то значит оно не получено. 
Надо тоже сделать такую константу.

https://github.com/arendst/Tasmota/search?q=START_VALID_TIME

const uint32_t START_VALID_TIME = 1451602800;  // Time is synced and after 2016-01-01

Сейчас должно работать так: если NTP не получено, то мы опять засыпаем. Так ли это?
Если не так, то надо сделать чтобы засыпали.

**Comment by neitri** [comment]
На мой взгляд, нужно синхронизацию времени выносить куда то выше. И сохранять флаг что время синхронизировано.
Подстройка времени работать будет только с синхронизацией времени обоих передач по расписанию. Т.е. если время не синхронизировано, то при следующей отправки подстроить время не удастся, т.к. время отправки показаний будет не корректное.
Как вариант пользовательский сервер времени использовать.

**Comment by dontsovcmc** [comment]
Пользователь подтвердил сбой периода
<img width="335" alt="Снимок экрана 2023-01-12 в 14 25 47" src="https://user-images.githubusercontent.com/6192152/212015692-9a6f9f04-39a1-4464-85d7-ff6a1c4a6bb3.png">

**Comment by vzagorovskiy** [comment]
fixed #249
