### ISSUE TITLE
Обновить версию WiFiManager

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#254]
WiFiManager выложен в декабре 2022 г.
Наш 2020г и можно обновить. Возможно это поможет с проблемными роутерами, т.к. первичное подключение именно WiFiManager делает.

**Comment by dontsovcmc** [comment]
> Hi, Have you included local Blynk server extra settings in this release?

Haven’t add..
But maybe you help us?
What parameters we should add to settings page?
host: string
port: integer
?

**Comment by Stas15** [comment]
Honestly I’m not good in programming, I’m just end user. But I believe if you could add host,IP and port for local Blynk server in WiFi manager it will be a great job which could solve issues with this integration. Thank you in advance.

**Comment by dontsovcmc** [comment]
> Just as mine pain, now I cannot connect waterius with mobile app. It connects, but dosnt send data to App, and sends only to your cloud. Im happy with it, but I liked it in my phone. I have no problems with my other projects, but to be honest, they much simpler then yours.

Do you have you own Blynk server?

**Comment by Stas15** [comment]
Yes, but it is not finished, there are few problems to solve

**Comment by Stas15** [comment]
Solved :)
