### ISSUE TITLE
Разные значения сенсора states.sensor.*.last_updated для общего и суточного потребления в HA

### ISSUE THREAD

**Issue by agav85** [dontsovcmc/waterius#261]
Это скорее вопрос: заметил, что у сенсоров холодной воды для общего и суточного потребления холодной воды установлены разные метки времени (разные значения last_updated). Для горячей воды - они идентичны. Не могу понять, почему так, ведь прибор передает данные один раз в сутки и сразу все.

Спасибо!

**Comment by dontsovcmc** [comment]
"сенсора суточного потребления в автодискавери не создаетс. Этот сенсор пользователь сам создал. Какое там будет last_updated только одному HA известно, когда он решит пересчитать сенсор суточного потребления. И уж точно тут больше удивительно не то что они не совпали  а то что они совпали."
