### ISSUE TITLE
Вебинтерфейс настройки: замечания, пожелания

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#277]
Здесь описаны текущие проблемы с веб-интерфейсом настройки. 
Также сюда можно писать пожелания по доработкам.

## Известные проблемы

1. Не понятно какая версия attiny, ESP.
При настройке, если проблемы, то хорошо бы это знать.
Решение: Пожелание добавить номера версий ESP и attiny на первую или страницу настроек (чтобы когда делали скриншот на нём было это видно)

2. Если MQTT топик пустой, добавлять косую черту принудительно)

## Уже решены

1. 0.11.9 При повторной настройке надпись "не подключено" сильно смущает пользователей — они опять выливают воду. 
Делать это не требуется.
Решение: в JS скрипте посмотреть - если указан вес импульса, то не показывать табличку.
При первой настройке в весе импульса указано "авто" и "как у холодной" - это признак, что юзер первый раз настраивает.
https://github.com/dontsovcmc/waterius/issues/206

2. 0.11.9: Изменение WIFI сети не удаляёт звёздочки в пароле. 
Решение: очищать поле пароль, если пользователь сменил WIFI сеть.

3. 0.11.9: На странице после Сохранить не отображается статус подключения Ватериуса к роутеру. По хорошему нужно отображать: плохой пароль и др. ошибки.

**Comment by dontsovcmc** [comment]
Известные мне проблемы:
1. При повторной настройке надпись "не подключено" сильно смущает пользователей — они опять выливают воду. 
Делать это не требуется.
Решение: в JS скрипте посмотреть - если указан вес импульса, то не показывать табличку.
При первой настройке в весе импульса указано "авто" и "как у холодной" - это признак, что юзер первый раз настраивает.

2. Изменение WIFI сети не удаляёт звёздочки в пароле. 
Решение: очищать поле пароль, если пользователь сменил WIFI сеть.

3. Не понятно какая версия attiny, ESP.
При настройке, если проблемы, то хорошо бы это знать.
Решение: Пожелание добавить номера версий ESP и attiny на первую или страницу настроек (чтобы когда делали скриншот на нём было это видно)

4. На странице после Сохранить не отображается статус подключения Ватериуса к роутеру. По хорошему нужно отображать: плохой пароль и др. ошибки.

**Comment by embisda** [comment]
![D647BD4D-5D71-4A29-9B70-06F55103E3BC](https://user-images.githubusercontent.com/19937071/235310288-76b4e2e7-36d7-4103-ac69-257b09833e92.jpeg)
Звездочки в поле пароль сбивают с толку. Непонятно что туда нужно вбивать пароль и поле на самом деле незаполнено

**Comment by dontsovcmc** [comment]
Если MQTT топик пустой, добавлять косую черту принудительно)

**Comment by dontsovcmc** [comment]
В 1.0.0 всё сделано. Ура, товарищи! =)
