### ISSUE TITLE
Второй раз фиксирую зависание устройства

### ISSUE THREAD

**Issue by wrewolf** [dontsovcmc/waterius#278]
Вот так выглядит в хом асистант, в чуство приходит нажатием кнопки для ручной отправки.
![image](https://user-images.githubusercontent.com/1876527/235760673-1bc5eb60-d57b-406b-a83d-504d3e2d8aef.png)

Завис около 18:00 27 апреля, только сейчас заметил тыкнул кнопочку и он послушно и без проблем отправил показания.

Версия программного обеспечения: 0.11.3.25
Версия аппаратного обеспечения: 1.0.0

**Comment by dontsovcmc** [comment]
хмм. а у вас на наш сайт отправляются данные? если да, пришлите мне адрес почты, пожалуйста.
А можете добавить в HA график параметра resets и boot?

**Comment by wrewolf** [comment]
Больше не повторялось. Создам новую проблему если будет повторяться
