### ISSUE TITLE
Включение логгирования на attiny85

### ISSUE THREAD

**Issue by ilyamordasov** [dontsovcmc/waterius#312]
Подскажите, при включении логгирования ругается
`main.ino:17:17: error: aggregate 'TinyDebugSerial mySerial' has incomplete type and cannot be defined`

define LOG_ON включил, либу по вашей ссылке скачал и подключил

**Comment by dontsovcmc** [comment]
Возможно она устарела… что то не корректно подключается либа. А какая операционная система?

**Comment by ilyamordasov** [comment]
ubuntu-latest

**Comment by dontsovcmc** [comment]
> ubuntu-latest
еще расскомментировать: 

lib_deps = 
     https://github.com/dontsovcmc/TinyDebugSerial#master
     
И поправить: LOG(info.config.resets);
