### ISSUE TITLE
Парсить и точку и запятую

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#313]
Пожелание от новичка:
При настройке и вводе первоначальных показаний желательно парсить не только точку, но и запятую. Я указал с запятой, система не ругнулась, но в итоге записались только целые числа.

**Comment by Anat0l** [comment]
Это стандартное поведение. 
https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/tofloat/

в при вводе значения можно использовать регулярное выражение ^[0-9]*[.]?[0-9]+$

**Comment by dontsovcmc** [comment]
В 1.1.1 добавил replace запятой на точку, чтобы toFloat срабатывала корректно

**Comment by dontsovcmc** [comment]
1.1.2
