### ISSUE TITLE
Добавить в discovery HA информацию о настройке полей

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#314]
HA знает только о том , что можно период поменять. А нужно еще добавить информацию про другие поля.

**Comment by Anat0l** [comment]
> HA знает только о том , что можно период поменять. А нужно еще добавить информацию про другие поля.

О каких полях идет речь? Можно подробней раскрыть мысль?

**Comment by dontsovcmc** [comment]
HA получает через discovery запрос информацию о параметрах устройства. В том числе информацию read / write. Сейчас только у периода есть write. А я добавил изменение и других полей, но не поменял информацию в discovery json

**Comment by Anat0l** [comment]
> HA получает через discovery запрос информацию о параметрах устройства. В том числе информацию read / write. Сейчас только у периода есть write. А я добавил изменение и других полей, но не поменял информацию в discovery json

еще раз спрошу, каких других полей?

**Comment by dontsovcmc** [comment]
> > HA получает через discovery запрос информацию о параметрах устройства. В том числе информацию read / write. Сейчас только у периода есть write. А я добавил изменение и других полей, но не поменял информацию в discovery json
> 
> еще раз спрошу, каких других полей?

вот здесь  в коде они есть: 
https://github.com/dontsovcmc/waterius/blob/fdfecc5f93b94369dfadd142dccf43055aac3f38/ESP8266/src/ha/subscribe.cpp#L51

**Comment by Anat0l** [comment]
в  ESP8266/src/ha/resources.h
Поменять тип на необходимых записях `sensor_type` с `s_sensor` на `s_number` 
Возможно понадобится дополнительная настройка для значений типа float

**Comment by dontsovcmc** [comment]
@Anat0l спасибо! 

Версия 1.1.2
