### ISSUE TITLE
Уведомление о замене батарейки

### ISSUE THREAD

**Issue by Anat0l** [dontsovcmc/waterius#316]
На сколько мне известно, информация о состоянии батарейки передаётся на сервер. Было бы неплохо сделать уведомление для пользователей в личном кабинете / электронным письмом о необходимости замены батареек по состоянию разряда или просто по времени.

**Comment by dontsovcmc** [comment]
К сожалению это трудно сделать, т.к. мы измеряем напряжение после стабилизатора.. На графиках оно просаживается,  как вариант собирать усредненный массив и смотреть на его производную если она отрицательная, то, да, скоро кончится батарейка... 
Если кто может помочь с этим ,готов выгрузить массив напряжений
