### ISSUE TITLE
Добавить ввод кол-ва импульсов для счетчиков электричества

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#327]
1. Если счетчик типа электричество, то нужна веб страница как в датчике Холла - ввод количества импульсов на киловатт. Также combobox с предустановленными значениями.

2. В коде esp добавить условие тип входа = электронный И тип воды = электричество = считать значение по другому

Друзья, напишите модель вашего счётчика и кол-во импульсов на 1 кВт, чтобы мы добавили в настройку

Счётчики:
Энергомера ЦЭ6803В 10-100А М7 Р31 - 3200 imp / KWh
http://files.energomera.ru/files/ce6803v__r32_front_400_400.jpg

Энергомера CE101 - 3200 imp / KWh

#электричество в тг

**Comment by EL-shadow** [comment]
У меня ce101 с 3200 imp / KWh
Но в паспорте энергомеры я видел что бывают модели с 2000 и 1600 imp / KWh
[Ссылка на паспорт](http://sp.energomera.ru/documentations/product/ce101_re.pdf)

**Comment by dontsovcmc** [comment]
1.1.5
