### ISSUE TITLE
Вотериус 2.0 - ESP32

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#39]
Хочется новую версию Вотериуса сделать на 1-й микросхеме.
Пишут, что ESP32 для этого замечательно подходит.

https://habr.com/post/418573/#comment_18937991
ULP Pulse Counting Example
examples/system/ulp/ вот что пишут:
With the default configuration (20ms ULP wakeup period), average current consumption in deep sleep mode is 16uA

Вопросы, идеи, помощь к: @IvKovalenko

**Comment by dontsovcmc** [comment]
https://www.instructables.com/id/ESP32-Deep-Sleep-Tutorial/

**Comment by OloloevReal** [comment]
Эксперимент с ESP32 и NB-IOT, дев версия. Если распаять модем, выкинуть лишние кнопки и разъемы то можно уменьшить раза в два размер

![](https://github.com/OloloevReal/Waterius32/raw/master/Board/device_v1_3.JPG "Waterius32")

**Comment by dontsovcmc** [comment]
Святые угодники!
1. Почему ЕСП32? Если можно обычный МК взять.
2. Что с автономностью?
3. Кто заказчик, если не секрет?
4. Опенсорс?
5. ULP  раскочегарили в ЕСП32?

**Comment by OloloevReal** [comment]
> Почему ЕСП32? Если можно обычный МК взять.

Так это уметь надо, а тут почти ардуино. Да и WiFi хочется иметь сразу из коробки

> Что с автономностью?

Т.к. хотел сделать питание от 4хАА или 18650 то пришлось использовать преобразователи. Конечно можно использовать элементы Li-SOCL2 и выбросить лишние элементы
В дип слип 20-30 мкА, не могу точнее замерить.

> Кто заказчик, если не секрет?
> Опенсорс?

Любопытство мой заказчик, интересно было посмотреть что же такое ESP32 и прикладное применение NB-IoT. Конечно опенсорс, использую адаптированную кодовую базу вотериуса

> ULP раскочегарили в ЕСП32?
Да, с института ничего не писал на ассемблере. Импульсы и датчики протечки считаются ulp. Вещь интересная, но со своими проблемами.

**Comment by dontsovcmc** [comment]
@OloloevReal это же превосходные новости! А напишите мне в телеграм @dontsovcmc или на почту, у меня вопросы есть!

**Comment by dontsovcmc** [comment]
Ух, что Амазон сделали!
ESP32: OTA обновления в Amazon FreeRTOS
https://www.terraelectronica.ru/news/6312

**Comment by dontsovcmc** [comment]
Обсуждение ESP32 версии предлагаю перенести сюда: https://github.com/OloloevReal/Waterius32, если @OloloevReal  не возражает!
