### ISSUE TITLE
Отправка показаний ГДЕ-КУДА-КАК

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#64]
### Друзья! Напишите в какой сайт/приложение вы передаёте показания! Вы увеличите полезность и применимость Ватериуса!

Для уточнения возможности добавления УК на сайт waterius.ru, напишите в contact@waterius.ru или телеграм @dontsovcmc данные для отправки показаний. Некоторые сайты добавить быстро, другие требуют больше времени.

# Добавлены на сайт
| где | компания | сайт | примечание |
| --- | --- | --- |  --- | 
| г. Москва | Москва | https://www.mos.ru | - | 
| г. Мурманк и Мурманская область | АО "МРИВЦ" | http://www.mrivc.ru/?page_id=234 | адрес | 
| г. Лыткарино | УК Комфорт | http://comfortuk.ru | логин, пароль от ЛК | 
| г. Ростов-на-Дону | | https://южныйокруг.рф | адрес, лиц.счет |
| г. Санкт-Петербург | | https://kvartplata.info | логин, пароль, счет |

# В разработке
| где | компания | сайт | примечание |
| --- | --- | --- |  --- | 
| -  | - | - | - |

# Остальные

г. Екатеринбург
https://frisbi24.ru/services/vodosnabzhenie

г. Новосибирск
https://narod.nskes.ru/ электричество 
https://www.gorvodokanal.com/fdebts/login.php вода 

г. Санкт-Петербург
https://lk.uksn.ru/index.php
Ленинградская область:
https://lk.epd47.ru/Account/LogOn

г. Москва
[x] https://www.mos.ru/services/catalog/popular/ ([правила](https://www.mos.ru/pgu/ru/services/link/2022/))
Домопульт

Подмосковье
https://мособлеирц.рф

г. Черкесск
mrc09.ru

г. Владивосток
https://play.google.com/store/apps/details?id=offo.vl.ru.offo

г. Ростов на дону
https://vodokanalrnd.ru/fastpay/send.php

**Comment by dontsovcmc** [comment]
ААА Уже всю работу кто-то проделал: http://schetchik-pokazanie.ru/

**Comment by dontsovcmc** [comment]
Санкт-Петербург
https://lk.uksn.ru/index.php

**Comment by Xa6ep** [comment]
Ростов-на-Дону
https://xn--c1afjenhpy1e1a.xn--p1ai/authorization
https://vodokanalrnd.ru/fastpay/send.php

**Comment by DimsterTim** [comment]
Нужна интеграция с [HomeAssistant](https://www.home-assistant.io)

**Comment by dontsovcmc** [comment]
> Нужна интеграция с [HomeAssistant](https://www.home-assistant.io)
Уже есть: https://github.com/dontsovcmc/waterius/issues/86
Будет круто, если поможете с инструкцией по настройке!

**Comment by DimsterTim** [comment]
Как я понял, предложенная интеграция была расчитана на встроенный MQTT брокер. Но этот функционал в HomeAssistant посчитали "велосипедом" и несколько версий как не поддерживают, а далее планируют убрать. Так что вся интеграция сводится к уже имеющемуся функционалу отправки данных на mqtt сервер. А в настройках HA в файле yaml уже вставляется предложенный код для "датчиков" с подпиской на топики mqtt в формате:
```
sensor:
  # waterius на кухне
  - platform: mqtt
    name: "Kitchen Cold Water"
    state_topic: "waterius/kitchen/ch0"
    value_template: "{{ value }}"
    unit_of_measurement: "м3"
    icon: mdi:water
```
где sensor - тип "датчика" в терминах НА
platform: mqtt - формат данных для датчика
name: - отображаемое название датчика
state_topic: - тема для подписки на обновления данных mqtt
value_template: - формат парсинга полученного от mqtt значения, в данном случае просто берется "значение" как есть, но может быть много вариантов, JSON, вычисления и тд.
unit_of_measurement: "м3" - очевидно, что единицы измерения для показаний
icon: - иконка из набора НА.

Таким образом для интеграции Waterius в НА вы настраиваете отправку данных на mqtt по имеющейся [инструкции для mqtt](https://github.com/dontsovcmc/waterius/blob/master/Mqtt.md). В НА нужно будет добавить в файл конфигурации .yaml "датчик" настроенный на обновления значений от mqtt сервера в формате, разобранном выше. Затем, в НА датчик "Kitchen_Cold_Water" используется для отображения данных или в алгоритмах автоматизации, [построении графиков](https://www.home-assistant.io/lovelace/sensor/).

**Comment by ddark008** [comment]
Ленобласть:
https://lk.epd47.ru/Account/LogOn

**Comment by dontsovcmc** [comment]
Коллеги, для уточнения возможности добавления УК на сайт waterius.ru, напишите в contact@waterius.ru или телеграм @dontsovcmc данные для входа в личный кабинет.

**Comment by dontsovcmc** [comment]
@DimsterTim т.е. HomeAssistant интегрируется без mqtt брокера и ничего кроме HomeAssistant не надо настраивать? Вы могли бы написать инструкцию, уверен она сэкономит многим время! Спасибо!

**Comment by DimsterTim** [comment]
@dontsovcmc Home Assistant (HA) интегрируется через mqtt. Собственно инструкция уже написана, там настройка HA на mqtt. Ничего другого не нужно.

**Comment by dontsovcmc** [comment]
@ddark008 нужны данные для входа на сайт.

**Comment by kcinIvan** [comment]
Привет, а как передаются данные на mos.ru? Какой нибудь скрипт на python и request?
Дело в том что вывел показания счетчика электроэнергии в homeassistant (Pzem-004t -> esp8266 -> mqtt -> hass), вот бы их теперь передавать автоматически. На счётчики воды планирую  waterius поставить. 
Может есть возможность сделать интеграцию для hass которая через сайт waterius будет передавать показания? Или через hass-> mqtt -> устройство waterius - >...

**Comment by dontsovcmc** [comment]
Привет, @kcinIvan ! Передаются от лица приложения на телефоне. Питон скрипт, глянь мои репозитории. Да, я могу добавить поддержку электрического счетчика на сайт Ватериуса, но для пары гиков это очень накладно делать =(. Тем более, что Pzem-004t не понятно с какой погрешностью считает..  Вам будет проще запускать самому Питон скрипт со своими данными для отправки показаний.

**Comment by kolobus** [comment]
1. ЕИС ЖКХ (C-300) - очень популярная коммерческая система для УК. Есть ЛК в вебе и мобильное приложение. 
Можно ещё у них напрямую спросить, может есть отдельный API даже.

2. Отправка на электронную почту прямо УК. У многих УК есть адрес куда можно отправлять показания, но это должен быть именно второй адрес и без подтверждения.

**Comment by dontsovcmc** [comment]
> 1. ЕИС ЖКХ (C-300) - очень популярная коммерческая система для УК. Есть ЛК в вебе и мобильное приложение.
>    Можно ещё у них напрямую спросить, может есть отдельный API даже.
> 2. Отправка на электронную почту прямо УК. У многих УК есть адрес куда можно отправлять показания, но это должен быть именно второй адрес и без подтверждения.

1. Когда я начал делать проект, то тоже подумал, покрыть максимум, а дальше как пойдет. Потом понял, что лучше другая модель - предложить клиентам самим выбирать, что добавить. Пока никто еис жкх не просил добавить.

2. Уже реализовали.

**Comment by svesh** [comment]
> > 1. ЕИС ЖКХ (C-300) - очень популярная коммерческая система для УК. Есть ЛК в вебе и мобильное приложение.
> >    Можно ещё у них напрямую спросить, может есть отдельный API даже.
> > 2. Отправка на электронную почту прямо УК. У многих УК есть адрес куда можно отправлять показания, но это должен быть именно второй адрес и без подтверждения.
> 
> 1. Когда я начал делать проект, то тоже подумал, покрыть максимум, а дальше как пойдет. Потом понял, что лучше другая модель - предложить клиентам самим выбирать, что добавить. Пока никто еис жкх не просил добавить.
> 2. Уже реализовали.

Как раз появилась потребность в отправке в C-300. Отправлю запрос через кабинет.

**Comment by dontsovcmc** [comment]
Тему закрываю. Нет потребности интегрировать все подряд. Сейчас добавляем по заявкам пользователей Ватериуса. Пока бесплатно. Дальше видно будет. Всем спасибо за участие =).
