### ISSUE TITLE
Счётчики электроэнергии

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#66]
Ватериус не поддерживает счётчики электроэнергии. 
Но это реально доделать, поэтому соберем марки с RS485 портом и узнаем потребность от вас.

СЭБ-2А.07Д.212
СЭБ-2А.07Д.212.1 http://electroschetchik.ru/seb-2a.07d.php
МАЯК 101АТД.132Ш.2ИО2Б RS-485 http://electroschetchik.ru/mayak%20101atd.php

Вот, что поддерживает УМ-31. Надо в яндексе посчитать популярность по запросам и начать...
```
ООО «НПК «Инкотекс» | Меркурий 200, 203.2Т, 206, 230, 233, 234, 236, 225.2
ФГУП «Нижегородский завод им. М.В.Фрунзе» | ПСЧ-3ТМ, ПСЧ-4ТМ, СЭТ-4ТМ, СЭБ-2А.07, СЭБ-2А.07Д, СЭБ-2А.08
ОАО «Концерн Энергомера» | СЕ102, СЕ102М, СЕ301, СЕ303
АО «Завод МЗЭП» | СТС-565/П5-400AP-2I5, СОЭ-55/60Ш-Т-215, СОЭ-55/60Ш-Т-217, СОЭ-55/60Ш-Т-415
ООО «ТАЙПИТ-ИП» | Нева МТ 113, 124, 313, 314, 324
ЗАО ПКК «МИЛАНДР» | Милур 104, 105, 305.11, 305.12, 305.32
ООО НПП «Тепловодохран» | ПУЛЬСАР исполнения РАДИО
ООО «Энрон-Энерго» | ТОПАЗ 103, 104
```

DIY проекты:
https://github.com/vad7/PowerMeter

**Comment by flystyle** [comment]
потребность есть
Меркурий 230 АRT http://electroschetchik.ru/m230art.php

**Comment by dontsovcmc** [comment]
1. Мне не понятно, имеют ли владельцы доступ к RS485 счетчиков - они же запломбированы?
Меркурий, добавим спасибо.

**Comment by flystyle** [comment]
Везде по разному, кто-то даёт доступ, кто-то нет, зависит от дремучести местного начальника электросетей. У меня счётчик с IrDA и подключён к ПК, но планирую переходить на RS485, заодно проверю, как сейчас дела обстоят с доступом к опломбированным интерфейсам.

**Comment by spqer** [comment]
SDM630 - трехфазный
SDM220 - однофазный.
Потребность есть, заказчики готовы ставить второй счетчик после опломбированного. В Питере ленэнерго все информационные выходы на своих счетчиках опечатывает

**Comment by dontsovcmc** [comment]
@spqer, а есть какие нибудь законодательные акты, что пользователь имеет право подключаться к информационным выходам? Это похоже на то, что Ленэнерго не хочет морочиться с разграничением доступа - нет сил, знаний, желания. Может есть какой то закон, который говорит, что "пользователь имеет право читать показания" со своего электросчетчика?
На подобии как "владелец жилья имеет право иметь ключи от крыши".

**Comment by spqer** [comment]
@dontsovcmc Когда у себя дома делал ремонт, представитель Ленэнерго которая опечатывала счетчик сослалась на свои внутренние инструкции. Я не уверен в их законности, но место в щите под еще один автомат найдется. Спасибо китайцам за маленькие счетчики)

Обычно, когда говоришь заказчику что придется как-то договариваться с нашим государством, вариант не терять время поставив доп устройство всех устраивает.

**Comment by Xa6ep** [comment]
А нельзя сделать с фоторезистором вариант, как у [LAVElek](https://habr.com/ru/post/428844/)?

**Comment by dontsovcmc** [comment]
@spqer Мастер из Мосэнергосбыта сказал, что запрещается пользователям подключаться к интерфейсу, т.к. админские пароли на Меркурий 200 известны всем и пользователь может тарифы поменять, чтобы меньше платить..

@Xa6ep да, это рабочий вариант. В интернете есть отличный проект на ESP.

**Comment by olegkyka** [comment]
> @Xa6ep да, это рабочий вариант. В интернете есть отличный проект на ESP.

Если не затруднит киньте ссылку почитать.

**Comment by dontsovcmc** [comment]
> > @Xa6ep да, это рабочий вариант. В интернете есть отличный проект на ESP.
> 
> Если не затруднит киньте ссылку почитать.
https://esp8266.ru/forum/threads/distancionnoe-snjatie-pokazanij-ehlektroschetchika-merkurij.2266/

**Comment by shum44** [comment]
посмотри как здесь сделали
https://sprut.ai/client/article/2184

**Comment by spoterianski** [comment]
http://incotex-counter.blogspot.com/2012/07/blog-post.html

**Comment by dontsovcmc** [comment]
Step UP преобразователи 
https://www.kirich.blog/stati/informaciya-dlya-nachinayuschih/136-para-step-up-konverterov-i-ih-nebolshoy-apgreyd-do-sepic.html

MT3608
-------
https://robotics.nethouse.ru/static/doc/0000/0000/0357/357325.ijcup4dklt.pdf с пином EN и 0.1мкА утечки. Кажется он тут: 
https://www.aliexpress.com/item/33009040632.html  20 руб
MT3608 3608 B6288

**Comment by Shagrat2** [comment]
Могу помочь с iek61107 - Счётчики Энергомера
Доступ к пинам с верхней крышки счётчика (не пломбируют). RS485 только отдельные модели.

Делал для:
HomeAssistent: https://github.com/Shagrat2/hassio-addons/tree/master/energomera-iek61107
MajorDomo: https://github.com/Shagrat2/majordomo-energomera

**Comment by dontsovcmc** [comment]
https://github.com/dontsovcmc/waterius/discussions/290
