### ISSUE TITLE
Проверить, не включается ли точка доступа при передаче

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#71]
есть ощущение, что точка доступа включается и при включении передачи показаний. проверить.

**Comment by OloloevReal** [comment]
Скорее всего включается, много раз наблюдал вот такую картину

![IMG_7233](https://user-images.githubusercontent.com/38255298/55676457-627f3a80-58de-11e9-8085-05e5e6ec0d9d.JPG)

Где значение в HEX после ESP_ уникальный ChipID ESP

Использую девелоперскую ветку [WiFiManager](https://github.com/tzapu/WiFiManager/tree/development)

**Comment by OloloevReal** [comment]
Возможно, нужно добавить 

`WiFi.mode(WIFI_STA);`
перед
` WiFi.begin();`

[#833](https://github.com/tzapu/WiFiManager/issues/833#issuecomment-466580488)

**Comment by dontsovcmc** [comment]
Хммм Спасибо!
Я такой космос сейчас делаю - опрос attiny во время работы вебсервера, чтобы сразу видеть, подключил ли провод или нет. И в следующей прошивке будет поддержка Намур. Ватериус сам разберется, что к нему подключили.

**Comment by dontsovcmc** [comment]
> Возможно, нужно добавить
> 
> `WiFi.mode(WIFI_STA);`

Так у меня же добавлена: 
https://github.com/dontsovcmc/waterius/blob/master/ESP8266/src/main.cpp#L78

**Comment by dontsovcmc** [comment]
Я сейчас hotfixes использую и у меня не появляется ESP_xxx  в списке сетей.

**Comment by dontsovcmc** [comment]
@OloloevReal ошибка подтверждается? у меня поиском сетей во время включения Ватериуса ничего не находит...

**Comment by OloloevReal** [comment]
@dontsovcmc у меня была ошибка с закомментированной строчкой WiFi.mode(WIFI_STA);, тянулась откуда-то из ранних версий + dev версия WifiManager (позволяет сделать темную тему оформления:) )
После того, как раскомментировал WiFi.mode(WIFI_STA); в списке сетей ничего подозрительного не видел.

**Comment by dontsovcmc** [comment]
Ура! =)
