### ISSUE TITLE
Ватериус NB-IoT

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/waterius#84]
Несколько компаний выразили желание видеть Ватериус с NB-IoT модулями.
Кто обладает опытом настройки и работы с NB-IoT сетями в РФ, пишите мне, есть выгодное предложение!

А пока, подходящие чипы:
BC95
BC68JA-02-STD

**Comment by OloloevReal** [comment]
А что конкретно интересует по NB-IoT
SIM7020E работает в РФ нормально, другие модемы в руках не держал

**Comment by dontsovcmc** [comment]
@OloloevReal давайте Ватериус с ним сделаем =)

**Comment by dontsovcmc** [comment]
Обсуждение NB-IoT версии предлагаю перенести сюда: https://github.com/OloloevReal/Waterius32, если @OloloevReal не возражает!
