### ISSUE TITLE
Ошибка в обозначении на плате

### ISSUE THREAD

**Issue by Shlepok** [dontsovcmc/waterius#87]
Ошибка в обозначении плюсовой клеммы питания во второй версии заводской платы. С разных сторон "+" стоит у разных контактов.
![IMG_20190709_162724](https://user-images.githubusercontent.com/4989059/60892370-bd228c80-a267-11e9-86df-76d9fd3fef89.jpg)

**Comment by dontsovcmc** [comment]
Уууух позор джунглей =(. Спасибо, поправлю!
Ошибка в TOP (верхней). Плюс дальше от края платы.

**Comment by dontsovcmc** [comment]
Исправил EagleCAD файлы.
