### ISSUE TITLE
ЛУТ - масштаб для печати

### ISSUE THREAD

**Issue by DimsterTim** [dontsovcmc/waterius#91]
Из документации не понятно в каком масштабе печатать PNG для ЛУТ. Пожалуйста добавьте информацию или выложите PDF файл - в нем масштаб сохранится.
Также, было бы здорово увидеть файл для распространенной Sprint Layout.

**Comment by dontsovcmc** [comment]
@DimsterTim ага, добавил 600 dpi 
https://github.com/dontsovcmc/waterius/blob/master/Making.md#%D0%B8%D0%B7%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5

для Sprint Layout некогда делать =(
